services:
  media_bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
    volumes:
      - .:/app
      - ./downloads:/app/downloads
      - ./logs.txt:/app/logs.txt
    # If you enabled a health dashboard, expose it here (example: 8080)
    # ports:
    #   - "8080:8080"
